---

- hosts: all
  become: true
  tasks:

  - name: update repo cache (Ubuntu)
    tags: centos
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  tasks:

  - name: add ssh key for simone
    tags: create
    authorized_key:
      user: simone
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINV3n7/kscYJ5hAX3CRWr5T/KTOEXlTi+QVMqAOft63H ansible"

- hosts: workstations
  become: true
  tasks:

  - name: install unzip
    package:
       name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

- hosts: web_servers
  become: true
  pre_tasks:
  
  - name: install apache and php for Ubuntu server
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu" 

#  - name: start apache2 (Ubuntu)
#    tags: apache,apache2, ubuntu, start
#    service:
#      name: apache2
#      state: started
#      enabled: yes
#    when: ansible_distribution == "Ubuntu"

  - name: change e-mail address for admin
    tags: apache, centos, httpd
    lineinfile:
      path: /etc/http/conf/httpd.conf
      regexp: '^ServerADmin'
      line: ServerAdmin somebody@somehwere.net
    when: ansible_distribution == "centoOS"
    register: httpd

  - name: restart httpd (centOS)
    tags: apache, centos, httpd
    service:
      name: httpd
      state: restarted
    when: httpd.changed

  - name: copy default html file or site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (Ubuntu)
    tags: db, mariadb, ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest
    when: ansible_distribution == "Ubuntu"
